#!/usr/bin/env python3

"""Add custom configs and default values"""
from fvcore.common.config import CfgNode

#pylint: disable=line-too-long

def add_custom_config(cfg):
    """Add custom configs."""
    cfg.DATA.PATH_TO_TROKEN_PT_DATA = '/fs/cfar-projects/actionloc/bounce_back/camera_ready/data/trokens_pt_data/'

    #wandb config
    cfg.WANDB = CfgNode()
    cfg.WANDB.PROJECT = 'trokens'
    cfg.WANDB.ENTITY = 'act_seg_pi_umd'
    cfg.WANDB.ID = ''
    cfg.WANDB.EXP_NAME = ''

    # few shot config
    cfg.FEW_SHOT = CfgNode()
    cfg.FEW_SHOT.N_WAY = 5
    cfg.FEW_SHOT.K_SHOT = 1
    cfg.FEW_SHOT.TRAIN_QUERY_PER_CLASS = 6
    cfg.FEW_SHOT.TEST_QUERY_PER_CLASS = 1
    cfg.FEW_SHOT.TRAIN_EPISODES = 100000
    cfg.FEW_SHOT.TEST_EPISODES = 10000
    cfg.FEW_SHOT.PATCH_TOKENS_AGG = 'spatial'
    cfg.FEW_SHOT.USE_MODEL = True
    cfg.FEW_SHOT.DIST_NORM = 'none'
    cfg.FEW_SHOT.TRAIN_OG_EPISODES = False
    cfg.FEW_SHOT.CLASS_LOSS_LAMBDA = 1.0
    cfg.FEW_SHOT.Q2S_LOSS_LAMBDA = 1.0
    cfg.FEW_SHOT.TEXT_ALIGN = CfgNode()
    cfg.FEW_SHOT.TEXT_ALIGN.ENABLE = False
    cfg.FEW_SHOT.TEXT_ALIGN.LOSS_WEIGHT = 0.1
    cfg.FEW_SHOT.TEXT_ALIGN.LOGIT_SCALE = 10.0
    cfg.FEW_SHOT.POT_ROUTE = CfgNode()
    cfg.FEW_SHOT.POT_ROUTE.ENABLE = False
    cfg.FEW_SHOT.POT_ROUTE.MU_LOGIT_SCALE = 10.0
    cfg.FEW_SHOT.POT_ROUTE.RHO_MIN = 0.2
    cfg.FEW_SHOT.POT_ROUTE.RHO_MAX = 0.9
    cfg.FEW_SHOT.POT_ROUTE.AFFINITY_TAU = 0.07
    cfg.FEW_SHOT.POT_ROUTE.KAPPA = 1.5
    cfg.FEW_SHOT.POT_ROUTE.ENTROPIC_EPS = 0.01
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_ENTROPIC_EPS = 0.03
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_MU_LOGIT_SCALE = 5.0
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_RHO_FRAME = 0.30
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_RHO_TRAJ = 0.50
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_RHO_VIS = 0.50
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_TARGET_MIX = 0.85
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_TOTAL_MASS = 1.0
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_TAU_FRAME = 0.12
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_TAU_TRAJ = 0.07
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_TAU_VIS = 0.07
    cfg.FEW_SHOT.POT_ROUTE.SHARED_TAU_LABEL = 0.07
    cfg.FEW_SHOT.POT_ROUTE.SHARED_THETA = 0.2
    cfg.FEW_SHOT.POT_ROUTE.SHARED_TAU_STRENGTH = 0.1
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_SHARED_ENABLE = False
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_SHARED_COST_WEIGHT = 0.5
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_SHARED_RATIO = 0.2
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_VIS_PRIVATE_WEIGHT = 1.0
    cfg.FEW_SHOT.POT_ROUTE.UOT3D_VIS_SHARED_WEIGHT = 1.0
    cfg.FEW_SHOT.POT_ROUTE.MAX_ITERS = 50
    cfg.FEW_SHOT.POT_ROUTE.STOP_TOL = 1e-4
    cfg.FEW_SHOT.POT_ROUTE.DEBUG_ENABLE = False
    cfg.FEW_SHOT.POT_ROUTE.DEBUG_FILE = "pot_3d_uot_debug.jsonl"
    cfg.FEW_SHOT.POT_ROUTE.DEBUG_LOG_PERIOD = 20
    cfg.FEW_SHOT.POT_ROUTE.DEBUG_MAX_RECORDS = 200
    cfg.FEW_SHOT.POT_ROUTE.DEBUG_MAX_SAMPLES_PER_CALL = 2
    cfg.FEW_SHOT.POT_ROUTE.DEBUG_TOPK = 8
    cfg.FEW_SHOT.POT_ROUTE.DEBUG_RANK0_ONLY = True
    cfg.FEW_SHOT.POT_ROUTE.DEBUG_RESET_FILE = True
    cfg.FEW_SHOT.POT_ROUTE.DEBUG_SAVE_TOP_TOKENS = True

    # point info config
    cfg.POINT_INFO = CfgNode()
    cfg.POINT_INFO.ENABLE = True
    cfg.POINT_INFO.GRID_SIZE = 16
    cfg.POINT_INFO.NAME = ''
    cfg.POINT_INFO.NUM_POINTS_TO_SAMPLE = 256
    cfg.POINT_INFO.SAMPLING_TYPE = 'random'
    cfg.POINT_INFO.PT_FIX_SAMPLING_TRAIN = False
    cfg.POINT_INFO.PT_FIX_SAMPLING_TEST = False
    cfg.POINT_INFO.USE_PT_QUERY_MASK = False
    cfg.POINT_INFO.OBJ_ID_KEY = 'obj_ids'
    cfg.POINT_INFO.HOD = CfgNode()
    cfg.POINT_INFO.HOD.NUM_BINS = 32
    cfg.POINT_INFO.HOD.NUM_CLUSTERS = 16
    cfg.POINT_INFO.HOD_MIN = True
    cfg.POINT_INFO.HOD.GET_FEAT = True
    cfg.POINT_INFO.HOD.TEMPORAL_PYRAMID = False
    cfg.POINT_INFO.HOD.TEMPORAL_PYRAMID_LEVELS = 3
    cfg.POINT_INFO.HOD.PRESERVE_TEMPORAL = True
    cfg.POINT_INFO.USE_CORRELATION = False

    # motion module config
    cfg.MODEL.MOTION_MODULE = CfgNode()
    cfg.MODEL.MOTION_MODULE.USE_CROSS_MOTION_MODULE = False
    cfg.MODEL.MOTION_MODULE.USE_HOD_MOTION_MODULE = False
    cfg.MODEL.APPEARANCE_MODULE_DISABLE = False

    return cfg
