#!/usr/bin/env python3

"""Add custom configs and default values"""
from fvcore.common.config import CfgNode

#pylint: disable=line-too-long

def add_custom_config(cfg):
    """Add custom configs."""
    cfg.DATA.PATH_TO_TROKEN_PT_DATA = '/fs/cfar-projects/actionloc/bounce_back/camera_ready/data/trokens_pt_data/'

    #wandb config
    cfg.WANDB = CfgNode()
    cfg.WANDB.PROJECT = 'trokens'
    cfg.WANDB.ENTITY = 'act_seg_pi_umd'
    cfg.WANDB.ID = ''
    cfg.WANDB.EXP_NAME = ''

    # few shot config
    cfg.FEW_SHOT = CfgNode()
    cfg.FEW_SHOT.N_WAY = 5
    cfg.FEW_SHOT.K_SHOT = 1
    cfg.FEW_SHOT.TRAIN_QUERY_PER_CLASS = 6
    cfg.FEW_SHOT.TEST_QUERY_PER_CLASS = 1
    cfg.FEW_SHOT.TRAIN_EPISODES = 100000
    cfg.FEW_SHOT.TEST_EPISODES = 10000
    cfg.FEW_SHOT.PATCH_TOKENS_AGG = 'spatial'
    cfg.FEW_SHOT.USE_MODEL = True
    cfg.FEW_SHOT.DIST_NORM = 'none'
    cfg.FEW_SHOT.TRAIN_OG_EPISODES = False
    cfg.FEW_SHOT.CLASS_LOSS_LAMBDA = 1.0
    cfg.FEW_SHOT.Q2S_LOSS_LAMBDA = 1.0
    cfg.FEW_SHOT.SUPPORT_TEXT_FUSION = CfgNode()
    cfg.FEW_SHOT.SUPPORT_TEXT_FUSION.ENABLE = False
    cfg.FEW_SHOT.SUPPORT_TEXT_FUSION.TEXT_WEIGHT = 1.0
    cfg.FEW_SHOT.SUPPORT_TEXT_FUSION.VISUAL_WEIGHT = 1.0
    cfg.FEW_SHOT.SUPPORT_TEXT_FUSION.VISUAL_DETACH = True
    cfg.FEW_SHOT.COST_AGG = CfgNode()
    cfg.FEW_SHOT.COST_AGG.ENABLE = False
    cfg.FEW_SHOT.COST_AGG.COST_DIM = 32
    cfg.FEW_SHOT.COST_AGG.GUIDANCE_DIM = 32
    cfg.FEW_SHOT.COST_AGG.NUM_HEADS = 4
    cfg.FEW_SHOT.COST_AGG.WINDOW_SIZE = 4
    cfg.FEW_SHOT.COST_AGG.NUM_LAYERS = 1
    cfg.FEW_SHOT.COST_AGG.MLP_RATIO = 4.0
    cfg.FEW_SHOT.COST_AGG.ATTN_DROPOUT = 0.0
    cfg.FEW_SHOT.COST_AGG.PROJ_DROPOUT = 0.0
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG = CfgNode()
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.ENABLE = False
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.GUIDANCE_DIM = 32
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.NUM_HEADS = 4
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.ATTENTION_TYPE = "full"
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.POOLING_SIZE = 1
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.PAD_LEN = 0
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.MLP_RATIO = 4.0
    cfg.FEW_SHOT.COST_AGG.CLASS_AGG.GATE_INIT = 0.0
    cfg.FEW_SHOT.TEXT_ALIGN = CfgNode()
    cfg.FEW_SHOT.TEXT_ALIGN.ENABLE = False
    cfg.FEW_SHOT.TEXT_ALIGN.LOSS_WEIGHT = 0.1
    cfg.FEW_SHOT.TEXT_ALIGN.LOGIT_SCALE = 10.0
    cfg.FEW_SHOT.POT_ROUTE = CfgNode()
    cfg.FEW_SHOT.POT_ROUTE.ENABLE = False
    cfg.FEW_SHOT.POT_ROUTE.FRAME_SOFTMAX_TAU = 0.07
    cfg.FEW_SHOT.POT_ROUTE.QUERY_PARTIAL_ENABLE = False
    cfg.FEW_SHOT.POT_ROUTE.QUERY_PARTIAL_LOGIT_ALPHA = 10.0
    cfg.FEW_SHOT.POT_ROUTE.QUERY_PARTIAL_LOGIT_BIAS = -2.0
    cfg.FEW_SHOT.POT_ROUTE.TEMPORAL_REFINEMENT = CfgNode()
    cfg.FEW_SHOT.POT_ROUTE.TEMPORAL_REFINEMENT.ENABLE = False
    cfg.FEW_SHOT.POT_ROUTE.TEMPORAL_REFINEMENT.TYPE = "lite_tcn_3ch_v1"
    cfg.FEW_SHOT.POT_ROUTE.TEMPORAL_REFINEMENT.HIDDEN_DIM = 16
    cfg.FEW_SHOT.POT_ROUTE.TEMPORAL_REFINEMENT.KERNEL_SIZE = 3
    cfg.FEW_SHOT.POT_ROUTE.TEMPORAL_REFINEMENT.LONG_DILATION = 2
    cfg.FEW_SHOT.POT_ROUTE.TEMPORAL_REFINEMENT.MAX_LOGIT_DELTA = 0.5
    cfg.FEW_SHOT.POT_ROUTE.TEMPORAL_REFINEMENT.WEIGHT_DECAY = 0.01
    # Optional visibility input channel; invalid observations are always masked.
    cfg.FEW_SHOT.POT_ROUTE.TEMPORAL_REFINEMENT.USE_VISIBILITY = True

    # Legacy 8.63 learned Null-token route, retained for ablation only.
    cfg.FEW_SHOT.QUERY_NULL_ROUTE = CfgNode()
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.ENABLE = False
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.SCORE_INIT = 0.07
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.SCORE_MIN = -0.20
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.SCORE_MAX = 0.80
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.CARDINALITY_CORRECTION = True
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.TOKEN_INIT_STD = 0.02
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.VALUE_SCALE = 1.0
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.DETACH_FRAME_SCALE = True
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.ORTHO_WEIGHT = 0.01
    cfg.FEW_SHOT.QUERY_NULL_ROUTE.ORTHO_DETACH_SUPPORT = True

    # Query-class matchability: pure text evidence estimates whether a Query
    # candidate should be trusted; text+Support routing still determines where.
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY = CfgNode()
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ENABLE = False
    # ``threshold`` preserves the 8.64 scalar Support-calibration route;
    # SAV's experiment config selects ``positive_confuser_margin``.
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.MODE = "threshold"
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.TOPK_PATCHES = 8
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.TOPK_FRAMES = 3
    # Evidence can come from the task-adapted Pointformer output ("post") or
    # from sampled DinoTxt tokens before positional/motion/Pointformer fusion.
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_SOURCE = "post"
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.CALIBRATION_BETA = 0.25
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.TEMPERATURE = 0.10
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.DETACH_SUPPORT_STATS = True
    # Relative positive/confuser mode controls.
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.MARGIN_TEMPERATURE = 0.10
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.MARGIN_BIAS = 0.0
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.NEGATIVE_AGGREGATION = "max"
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.NEGATIVE_TOPK = 2
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.NEGATIVE_TEMPERATURE = 0.10
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.DETACH_CONFUSER_SUPPORT = False
    # Optional local positive-vs-confuser patch refinement.  The generic
    # default is disabled so callers that only request the scalar
    # matchability branch retain the pre-8.65 route.
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.LOCAL_REFINEMENT_ENABLE = False
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.LOCAL_MARGIN_TEMPERATURE = 0.10
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.LOCAL_LOGIT_STRENGTH = 0.50
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.LOCAL_POSITIVE_AGGREGATION = (
        "topk_mean"
    )
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.LOCAL_POSITIVE_TOPK = 2
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.LOCAL_NEGATIVE_AGGREGATION = (
        "topk_mean"
    )
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.LOCAL_NEGATIVE_TOPK = 2
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.LOCAL_NEGATIVE_TEMPERATURE = 0.10
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.LOCAL_DETACH_REFERENCES = True
    # Optional frame verifier. It compares Positive and Confuser explanations
    # on the same class-conditioned region pi that constructs Q_k.
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_VERIFICATION_ENABLE = False
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_USE_VISIBILITY = True
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_POSITIVE_AGGREGATION = (
        "topk_mean"
    )
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_POSITIVE_TOPK = 2
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_CONFUSER_AGGREGATION = (
        "topk_mean"
    )
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_CONFUSER_TOPK = 2
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_AGGREGATION_TEMPERATURE = 0.10
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_DETACH_REFERENCES = True
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.FRAME_MARGIN_TEMPERATURE = 0.10
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.FRAME_MARGIN_BIAS = 0.0
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_VIDEO_TOPK_FRAMES = 3
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_MIL_TEMPERATURE = 0.10
    # Disabled generically; individual experiments can opt into the
    # video-label MIL objective without changing compatibility callers.
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.EVIDENCE_MIL_LOSS_WEIGHT = 0.0
    # Optional Support-calibrated absolute non-null mass. When frame evidence
    # is also enabled, the matcher transports only target mass g=m*rho.
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_ENABLE = False
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_SOURCE = "raw"
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_USE_VISIBILITY = True
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_PATCH_TOPK = 8
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_SUPPORT_TOPK_FRAMES = 3
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_CALIBRATION_BETA = 0.25
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_TEMPERATURE = 0.05
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_MIN_SUPPORT_GAP = 0.0
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_DETACH_SUPPORT_STATS = True
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_RELIABILITY_FALLBACK = True
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_TRANSPORT_STRENGTH = 1.0
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_UNMATCHED_COST = 0.0
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.ABSOLUTE_MASS_ONE_SIDED = True
    # Keep the original and verified q2s objectives separately supervised
    # when local refinement is enabled.  Disabled by default for compatibility.
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.DUAL_LOGIT_LOSS_ENABLE = False
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.BASE_LOGIT_LOSS_WEIGHT = 0.50
    cfg.FEW_SHOT.QUERY_CLASS_MATCHABILITY.VERIFIED_LOGIT_LOSS_WEIGHT = 0.50

    # point info config
    cfg.POINT_INFO = CfgNode()
    cfg.POINT_INFO.ENABLE = True
    cfg.POINT_INFO.GRID_SIZE = 16
    cfg.POINT_INFO.NAME = ''
    cfg.POINT_INFO.NUM_POINTS_TO_SAMPLE = 256
    cfg.POINT_INFO.SAMPLING_TYPE = 'random'
    cfg.POINT_INFO.PT_FIX_SAMPLING_TRAIN = False
    cfg.POINT_INFO.PT_FIX_SAMPLING_TEST = False
    cfg.POINT_INFO.USE_PT_QUERY_MASK = False
    cfg.POINT_INFO.OBJ_ID_KEY = 'obj_ids'
    cfg.POINT_INFO.HOD = CfgNode()
    cfg.POINT_INFO.HOD.NUM_BINS = 32
    cfg.POINT_INFO.HOD.NUM_CLUSTERS = 16
    cfg.POINT_INFO.HOD_MIN = True
    cfg.POINT_INFO.HOD.GET_FEAT = True
    cfg.POINT_INFO.HOD.TEMPORAL_PYRAMID = False
    cfg.POINT_INFO.HOD.TEMPORAL_PYRAMID_LEVELS = 3
    cfg.POINT_INFO.HOD.PRESERVE_TEMPORAL = True
    cfg.POINT_INFO.USE_CORRELATION = False

    # motion module config
    cfg.MODEL.MOTION_MODULE = CfgNode()
    cfg.MODEL.MOTION_MODULE.USE_CROSS_MOTION_MODULE = False
    cfg.MODEL.MOTION_MODULE.USE_HOD_MOTION_MODULE = False
    cfg.MODEL.APPEARANCE_MODULE_DISABLE = False

    return cfg
